# Generated by Django 5.1.1 on 2024-10-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=100)),
                ('email_aluno', models.EmailField(max_length=254)),
                ('telefone_aluno', models.CharField(max_length=20)),
                ('data_nascimento_aluno', models.DateField()),
                ('instituicao_escolar', models.CharField(max_length=100)),
                ('serie_escolar', models.CharField(max_length=50)),
                ('sexo_aluno', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=10)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=20)),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('cpf_responsavel', models.CharField(max_length=14)),
                ('rg_responsavel', models.CharField(max_length=12)),
                ('email_responsavel', models.EmailField(max_length=254)),
                ('telefone_responsavel', models.CharField(max_length=20)),
                ('data_nascimento_responsavel', models.DateField()),
                ('profissao_responsavel', models.CharField(max_length=100)),
                ('sexo_responsavel', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=10)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
